Assignment1/eStoreClient/Controllers/AuthController.cs
using eStoreClient.Models.Auth;
using eStoreClient.Services.Interfaces;
using eStoreClient.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace eStoreClient.Controllers
{
	public class AuthController : Controller
	{
		private readonly IAuthService _authService;
		private readonly ITokenProvider _tokenProvider;
		public AuthController(IAuthService _authService, ITokenProvider tokenProvider)
		{
			this._authService = _authService;
			_tokenProvider = tokenProvider;
		}
		[HttpGet]
		public IActionResult Register()
		{
			return View(new CreateMemberDTO());
		}
		[HttpPost]
		public async Task<IActionResult> Register(CreateMemberDTO model)
		{
			if (!ModelState.IsValid)
			{
				return View(model);
			}
			else
			{
				var result = await _authService.RegisterAsync(model);
				if (result is not null && result.IsSuccess)
				{
					TempData["success"] = "Register successfully!";
					return RedirectToAction(nameof(Login));
				}
				else
				{
					return View(model);
				}
			}
		}
		[HttpGet]
		public IActionResult Login()
		{
			LoginRequestDTO loginRequestDTO = new();
			return View(loginRequestDTO);
		}
		[HttpGet]
		public async Task<IActionResult> Logout()
		{
			_tokenProvider.ClearToken();
			await HttpContext.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public async Task<IActionResult> Login(LoginRequestDTO model)
		{
			ResponseDTO? response = await _authService.LoginAsync(model);
			if (response is not null && response.IsSuccess)
			{
				LoginResponseDTO? responseDTO = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result)!);
				await SignInUser(responseDTO!);
				_tokenProvider.SetToken(responseDTO!.Token);
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ModelState.AddModelError("CustomError", response!.Message);
				return View(model);
			}
		}

		private async Task SignInUser(LoginResponseDTO model)
		{
			// Get Token, Read Token, And assign claims into identity
			var handler = new JwtSecurityTokenHandler();
			var jwt = handler.ReadJwtToken(model.Token);
			var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
			identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email)!.Value));
			identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Sub)!.Value));
			identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email)!.Value));
			identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(x => x.Type == "role")!.Value));
			var principal = new ClaimsPrincipal(identity);
			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
		}
	}
}

Assignment1/eStoreClient/Controllers/MemberController.cs
using eStoreClient.Models.Auth;
using eStoreClient.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace eStoreClient.Controllers
{
	public class MemberController : Controller
	{
		private readonly IMemberService _memberService;
		public MemberController(IMemberService memberService)
		{
			_memberService = memberService;
		}
		[HttpGet]
		public IActionResult Index()
		{

			return View();
		}

		[HttpGet]
		public async Task<IActionResult> Details(Guid id)
		{
			var result = await _memberService.GetMemberById(id);
			if (result is not null && result.IsSuccess)
			{
				return View(JsonConvert.DeserializeObject<MemberDTO>(Convert.ToString(result.Result)!));
			}
			else
			{
				TempData["error"] = "Not found";
				return RedirectToAction(nameof(Index));
			}
		}

		[HttpGet]
		public async Task<IActionResult> Profile(string email)
		{
			var result = await _memberService.GetByEmail(email);
			if (result is not null && result.IsSuccess)
			{
				var member = JsonConvert.DeserializeObject<MemberDTO>(Convert.ToString(result.Result)!);
				return View(new UpdateMemberDTO
				{
					Id = member!.Id,
					City = member.City,
					CompanyName = member.CompanyName,
					Country = member.Country,
					Email = member.Email,
					Password = member.Password,
					RoleName = member.RoleName
				});
			}
			else
			{
				TempData["error"] = "Not found";
				return RedirectToAction(nameof(Index));
			}

		}
		[HttpPost]
		public async Task<IActionResult> Profile(MemberDTO member)
		{
			var result = await _memberService.UpdateMemberProfile(member);
			if (result is not null && result.IsSuccess)
			{
				TempData["success"] = "Update your profile successfully!";
				return RedirectToAction(nameof(Profile), new { email = member.Email });
			}
			else
			{
				TempData["error"] = result!.Message;
				return View(member);
			}
		}

		[HttpGet]
		public async Task<IActionResult> Delete(Guid id)
		{
			var result = await _memberService.GetMemberById(id);
			if (result is not null && result.IsSuccess)
			{
				return View(JsonConvert.DeserializeObject<MemberDTO>(Convert.ToString(result.Result)!));
			}
			else
			{
				TempData["error"] = "Not found";
				return RedirectToAction(nameof(Index));
			}
		}

		[HttpPost]
		public async Task<IActionResult> Delete(MemberDTO member)
		{
			var result = await _memberService.DeleteMember(member.Id);
			if (result is not null && result.IsSuccess)
			{
				TempData["success"] = "Delete member successfully!";
				return RedirectToAction(nameof(Index));
			}
			else
			{
				TempData["error"] = "Delete member failed!";
				return RedirectToAction(nameof(Delete), new { id = member.Id });

			}

		}
	}
}

Assignment1/eStoreClient/Controllers/OrderController.cs
using eStoreClient.Models.OrderDTO;
using eStoreClient.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace eStoreClient.Controllers
{
	public class OrderController : Controller
	{
		private readonly IOrderService _orderService;
		private readonly IMemberService _memberService;
		public OrderController(IOrderService orderService, IMemberService memberService)
		{
			_orderService = orderService;
			_memberService = memberService;
		}
		public async Task<IActionResult> Index()
		{
			var result = await _orderService.GetAllOrders();
			if (result is not null && result.IsSuccess)
			{
				var orderList = JsonConvert.DeserializeObject<IEnumerable<OrderViewDTO>>(Convert.ToString(result.Result)!);
				return View(orderList);
			}
			else
			{
				TempData["error"] = "Not have any orders!";
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpGet]
		public async Task<IActionResult> Details(Guid id)
		{
			var result = await _orderService.GetOrderById(id);
			if (result is not null && result.IsSuccess)
			{
				var order = JsonConvert.DeserializeObject<OrderViewDTO>(Convert.ToString(result.Result)!);
				return View(order);
			}
			else
			{
				TempData["error"] = "Not found!";
				return RedirectToAction(nameof(Index));
			}
		}

		[HttpGet]
		public async Task<IActionResult> OrderHistory(Guid id)
		{

			var result = await _orderService.GetOrderByUser(id);
			if (result is not null && result.IsSuccess)
			{
				var orderList = JsonConvert.DeserializeObject<IEnumerable<OrderViewDTO>>(Convert.ToString(result.Result)!);
				return View(nameof(Index), orderList);
			}
			else
			{
				TempData["error"] = "You have not ordered anything yet!";
				return RedirectToAction("Index", "Home");
			}
		}

		[HttpPost]
		public async Task<IActionResult> Filter(DateTime startDate, DateTime endDate)
		{
			var result = await _orderService.GetOrderByDate(startDate, endDate);
			if (result is not null && result.IsSuccess)
			{
				var orderList = JsonConvert.DeserializeObject<IEnumerable<OrderViewDTO>>(Convert.ToString(result.Result)!);
				return View(nameof(Index), orderList);
			}
			else
			{
				TempData["error"] = "Not found any Orders in the range of date you input";
				return RedirectToAction(nameof(Index));
			}

		}




	}
}

Assignment1/eStoreClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore_Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mango.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    
                    <li class="nav-item dropdown">
                        @if(User.IsInRole("ADMIN"))
                        {
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Member" asp-action="Index">Member</a></li>

                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Product</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Order" asp-action="Index">Order </a></li>
                            </ul>
                        } else if(User.IsInRole("MEMBER"))
                        {
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Order" asp-action="OrderHistory" asp-route-id="@User.Identities.First().Claims.FirstOrDefault(x => x.Type == "sub")!.Value">View Your Orders</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Member" asp-action="Profile" asp-route-email="@User.Identities.First().Claims.First(x => x.Type == "email").Value">Profile</a></li>
                            </ul>
                        }
                        
                    </li>
                </ul>
                <ul class="navbar-nav">
                    @if (!User.Identity!.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello @User.Identities.First().Claims.FirstOrDefault(x => x.Type == "name")!.Value</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cart/Index">View Your Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    }
                </ul>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_NotificationPartial"></partial>
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            <div class="text-center">
                &copy; Aug_2023_Trang Minh Quang

            </div>




        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Assignment1/eStoreClient/Views/Shared/_NotificationPartial.cshtml
@if(TempData["error"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" >
        toastr.error('@TempData["error"]')
        </script>
}

@if (TempData["success"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}